name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [pspdev/pspdev]

    container: ${{ matrix.docker_tag }}:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake
    
    - name: Compile & Install SDL2
      run: |
        git clone -b psp-render-to-texture-attempt-2 https://github.com/stdgregwar/SDL.git 
        cd SDL && mkdir build && cd build 
        psp-cmake ..
        make -j$(getconf _NPROCESSORS_ONLN)
        make -j$(getconf _NPROCESSORS_ONLN) install

    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake -DCMAKE_INSTALL_PREFIX=${PSPDEV}/psp -DBUILD_SHARED_LIBS=OFF -DUSE_OPENAL=OFF -DIntl_INCLUDE_DIR=${PSPDEV}/psp/include ..
        make -j$(getconf _NPROCESSORS_ONLN)
        
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: openomf-${{ steps.slug.outputs.sha8 }}
        path: |
          build/openomf
          build/EBOOT.PBP